### ISSUE TITLE
Upgrade duckdb-wasm and apache-arrow

### ISSUE THREAD

**Issue by tobilg** [holdenmatt/duckdb-wasm-kit#18]
Could you please upgrade the duckdb-wasm and apache-arrow? The latest version https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.28.1-dev258.0 uses Arrow v17 instead of v15 a well:

https://github.com/duckdb/duckdb-wasm/blob/main/packages/duckdb-wasm/package.json#L26

I can create a PR if you like. Thanks!

**Comment by holdenmatt** [comment]
Sorry for delay.

I just pushed a new version that makes @duckdb/duckdb-wasm a peer dependency instead. This way you can update the core duckdb version as you like, without blocking on me :)

You'll need to `npm install @duckdb/duckdb-wasm` in your project, if you haven't already.

I've tested and everything seems to work, but let me know if you have any issues with this change.

**Comment by tobilg** [comment]
hm, I'm trying to use a recent dev version and seeing this error:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: testv2@0.0.0
npm ERR! Found: @duckdb/duckdb-wasm@1.28.1-dev271.0
npm ERR! node_modules/@duckdb/duckdb-wasm
npm ERR!   @duckdb/duckdb-wasm@"1.28.1-dev271.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @duckdb/duckdb-wasm@"^1.28.0" from duckdb-wasm-kit@0.1.36
```

**Comment by holdenmatt** [comment]
Thanks, I pushed a new version, can you try again?

Looks like the dev version numbers aren't working with `^1.28.0` (it works in yarn, but not in npm).

For now, I made the peer dependency versioning very loose:
```
    "@duckdb/duckdb-wasm": "*",
    "apache-arrow": ">=15.0.0",
```

I think that should be fine, as this library doesn't depend on anything from duckdb-wasm that's likely to break. But let me know if you run into any issues.

I tested it works with "1.28.1-dev258.0" (but it looks like newer versions are currently [broken](https://github.com/duckdb/duckdb-wasm/issues/1838))

**Comment by simonprovost** [comment]
@holdenmatt @tobilg I am not sure if my issue is related but I am having a `duckdb.getJsDelivrBundles is not a function` when I try to use DuckDB-wasm-kit in my current project. I tried and found that @tobilg referenced something similar around here https://github.com/duckdb/duckdb-wasm/issues/1542#issuecomment-1877511526 – May I know what should I do with the versioning please? this is pretty confusing 

Had the following and tried the following:

```
...
    "@duckdb/duckdb-wasm": "^1.29.0",
    "duckdb-wasm-kit": "^0.1.38",
```

```json
...
    "@duckdb/duckdb-wasm": "1.28.1-dev258.0",
    "duckdb-wasm-kit": "0.1.38",
...
```

Everything seems to be starting from: 

```js
const PreloadDuckDB = () => {
  useEffect(() => {
    const config: DuckDBConfig = {
      path: "/<my_db_path in the /public folder>.duckdb",
      query: { castBigIntToDouble: true },
    };

    initializeDuckDb({ config, debug: true });
  }, []);
  return null;
};
```

**Comment by simonprovost** [comment]
Re @holdenmatt 

If we take the following examples for me it does not work – with the following error `duckdb.getJsDelivrBundles is not a function`  –– Is the issue with my duck db database's instance? It works when using DuckDB in node.js without WASM. Same instance.

Here is a minimal and rapid reproducible example:

Package.json
```json
{
  "name": "<name>",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@duckdb/duckdb-wasm": "^1.29.0", # tried with "@duckdb/duckdb-wasm": "1.28.1-dev211.0",
    "duckdb-wasm-kit": "^0.1.38",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^7.1.3",
    "react-scripts": "5.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "web-vitals": "^4.2.4"
  }
}

```

App.js
```js
import React from "react";
import { BrowserRouter as Router } from "react-router-dom";
import DuckDbProvider from "./DuckDBProvider";
import PreloadDuckDB from "./DuckDBPreload";

const App = () => (
  <Router>
    <PreloadDuckDB />
    <DuckDbProvider>
      <div>App</div>
    </DuckDbProvider>
  </Router>
);

export default App;
```

DuckDBPreload.js
```js
import { useEffect } from "react";
import { initializeDuckDb } from "duckdb-wasm-kit";

const PreloadDuckDB = () => {
  useEffect(() => {
    initializeDuckDb({
      config: { path: "/<my_db_instance_in_the_public_folder>.duckdb", query: { castBigIntToDouble: true } },
      debug: true,
    });
  }, []);

  return null;
};

export default PreloadDuckDB;
```


DuckDBProvider.js
```js
import React from "react";
import { useDuckDb } from "duckdb-wasm-kit";

const DuckDbProvider = ({ children }) => {
  const { loading, error } = useDuckDb();

  if (loading) return <div>Loading Database...</div>;
  if (error) return <div>Error loading database: {error.message}</div>;

  return <>{children}</>;
};

export default DuckDbProvider;
```

**Comment by tobilg** [comment]
You can’t set a path for the db. It‘s in-memory…

See https://github.com/ownstats/ownstats/blob/main/frontend/src/main.tsx#L19 which works for me.

**Comment by simonprovost** [comment]
Thanks for your answer 🙏 Okay that's what I believed! So where do you setup/load/whatever the term your parquet/csv/whatever data you use please ? 

Cheers

**Comment by simonprovost** [comment]
Rest of the discussion I mentioned is moving in #14.

**Comment by holdenmatt** [comment]
Closing, as the original issue here should be done.
